# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 483e05de042924dfe1f77ce3462f10a1edf2261cd8dbeb192aacc7ffc2ae499df91464caebfa20936ddaff5d7dc8699487a141dba66a450b1fc686a1a049b327

test:
  secret_key_base: 66221e03e320bd63ae8d607de23f9d45e2f083d3823cc5337bb539cc3600dafde326a29f47a629eb2987e5b0b6371000e4cdad8fbb1101533db317900a7ca4c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
